version: '3.4'

services:
  catalog-api:
    image: catalog-api:v1
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}