# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalog-api:
    image: catalog-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
